### ISSUE TITLE
Spotify auth tokens don't get refreshed

### ISSUE THREAD

**Issue by orrc** [zaccolley/songkick-spotify-previews#3]
Thanks for the super-useful plugin!

However, if the auth token expires — which currently seems to happen roughly every ~24~ few hours — the plugin silently fails, and no Spotify info is shown on the page.

It would be great if the auth tokens could be refreshed automatically as required.
Or at least, delete the auth tokens from local storage if `api.spotify.com` returns a 401 error.

My current workaround:
1. Open the Developer Tools
2. Choose the Application tab
3. Navigate to Storage > Local Storage
4. Delete the two `songkickSpotifyPreviews*` keys
5. Refresh the page
6. Re-authenticate with Spotify :tada:

**Comment by zoetrope69** [comment]
Thanks for the detailed response.

Gonna see if I can renew the token.

**Comment by zoetrope69** [comment]
As I'm using the implicit grant flow: https://developer.spotify.com/web-api/authorization-guide/#implicit_grant_flow

I think I need to just let your reauth if it expires

**Comment by zoetrope69** [comment]
Thanks @orrc let me know if that works for you, just publishing the new version now.

**Comment by orrc** [comment]
Yes, it works great! Thanks for the speedy fix.
